version: '3'
services:
  server:
    container_name: martian_robots_server
    build: .
    ports:
      - '9000:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
